### ISSUE TITLE
Cannot validate certificate because it doesn't contain any IP SAN

### ISSUE THREAD

**Issue by matskr90dev** [bradbeck/nexus-https#5]
Hi, I would like to use Your image in my Docker test instance (I use Docker Toolbos for Windows). 

I used this command to run image:
`docker run -d -p 8081:8081 -p 8443:8443 -v ~/nexus-data:/nexus-data -v ~/nexus-ssl:/opt/sonatype/nexus/etc/ssl --name nexus bradbeck/nexus-https`

The nexus repository is started successfully but when I created docker hosted repository and I tried login to them I got this error.

![przechwytywanie](https://user-images.githubusercontent.com/8293063/30339594-ce5769aa-97ef-11e7-99b0-3e18275813fc.PNG)

**Comment by bradbeck** [comment]
You would need to configure a port for https on your docker hosted repository (e.g. 8888). Make sure that port also gets mapped with a '`-p 8888:8888`' on you run command. Then use that port when using docker against it (e.g. `docker login 192.168.99.100:8888`)

**Comment by CMYanko** [comment]
Looks like your trying to log into nexus instead of a docker repo. I tend to add two more ports for docker SSL. 18443 (docker read group) and 18444 (docker private repo).

**Comment by SylvainVISSIERE-GUERINET** [comment]
It reminds me of issues i had on CentOS 7.2, default openssl configuration does not specify any SAN(subjectAltName), i cloned this repo, produce a openssl.cnf file with SAN working for me, create a Dockerfile based on @bradbeck one and copy openssl.cnf into /etc/pki/tls/openssl.cnf.

By the way, i don't know if this issue is related only to CentOS or openssl.

**Comment by leochan007** [comment]
already binding 8443 but still had the problem.

docker run  --restart always -d -p 8081:8081 -p 8443:8443 -p 8085:8085 -p 8089:8089 -v /data/nexus-data:/nexus-data -v /data/nexus-ssl:/opt/sonatype/nexus/etc/ssl --name nexus bradbeck/nexus-https

docker login -u admin -p admin123 [IP]:8443
Error response from daemon: Get https://[IP]:8443/v1/users/: x509: cannot validate certificate for [IP] because it doesn't contain any IP SANs

**Comment by leochan007** [comment]
@bradbeck any suggestions? thx.

**Comment by bradbeck** [comment]
@leochan007 You might have better luck using a reverse proxy (e.g. nginx) for SSL termination and routing to docker repository endpoints.

There is some info here: https://support.sonatype.com/hc/en-us/articles/360000761828-Docker-Repository-Reverse-Proxy-Strategies
